### ISSUE TITLE
Error in gradle

### ISSUE THREAD

**Issue by RoberV** [mrkcsc/android-media-picker#16]
Hi! When I try to import to gradle. I have this error:
`Error:Failed to resolve: me.villani.lorenzo.android:android-cropimage:1.+`

How I can solve it?

**Comment by mrkcsc** [comment]
You must include the repository of `cropimage` within your top level `build.gradle` file for the dependency to resolve.

`https://github.com/mrkcsc/android-media-picker#configuration`

```
allprojects {

    repositories {
        jcenter()

        maven {
            url 'http://lorenzo.villani.me/android-cropimage/'
        }
    }
}
```

The library dependency will likely be removed in the future.
